server:
  port: 7071

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserDB2
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
